/**
 * Custom service worker for AgroScan NG.
 *
 * Strategy:
 *  - App shell (HTML / JS / CSS / icons) → CacheFirst via Workbox precaching.
 *  - API calls (/api/*) → NetworkOnly (diagnoses always require connectivity).
 *  - Navigation fallback → serve the cached index.html (SPA routing).
 *
 * Vite-plugin-pwa injects the precache manifest at build time via
 * self.__WB_MANIFEST.
 */
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { registerRoute, NavigationRoute } from 'workbox-routing'
import { NetworkOnly, CacheFirst } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<{ url: string; revision: string | null }> }

// Precache the app shell generated by Vite
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// API requests are always network-only (live inference required)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkOnly()
)

// Static assets: cache-first with a 30-day expiry
registerRoute(
  ({ request }) =>
    request.destination === 'image' ||
    request.destination === 'font' ||
    request.destination === 'style' ||
    request.destination === 'script',
  new CacheFirst({
    cacheName: 'static-assets-v1',
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  })
)

// SPA fallback: serve cached index.html for navigation requests
const navigationRoute = new NavigationRoute(
  new CacheFirst({ cacheName: 'shell-v1' })
)
registerRoute(navigationRoute)
